# Generated by Django 4.0.3 on 2022-03-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodelclass',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodelclass',
            name='price',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
