# Generated by Django 4.0.3 on 2022-03-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0004_alter_productmodelclass_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodelclass',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='productmodelclass',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
