# Generated by Django 4.0.3 on 2022-03-04 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0005_alter_productmodelclass_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductModelClass',
            new_name='ProductModel',
        ),
    ]
