# Generated by Django 4.0.3 on 2022-04-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0006_rename_productmodelclass_productmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='moreDescription',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='otherstuff',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
