# Generated by Django 4.0.3 on 2022-04-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0007_productmodel_moredescription_productmodel_otherstuff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='description',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
