# Generated by Django 4.0.3 on 2022-05-08 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0010_costumer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costumer',
            options={},
        ),
        migrations.AlterModelManagers(
            name='costumer',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='costumer',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='costumer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='costumer',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='costumer',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='costumer',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='costumer',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='costumer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='costumer',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='costumer',
            name='cart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pro.cart'),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='costumer',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
