# Generated by Django 4.0.3 on 2022-05-13 08:42

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0011_alter_costumer_options_alter_costumer_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='costumer',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='costumer',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
